apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
   replicas: 1
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - name: con1
         image: nginx:latest
         ports: 
         - containerPort: 80
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: cpu
                 operator: NotIn # 1. In for affinity # 2. NotIn for AntiAffinity
                 values:
                 - ryzen
