apiVersion: apps/v1
kind: Deployment
metadata:
  name: podaff
spec:
   replicas: 1
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - name: con1
         image: nginx:latest
         ports: 
         - containerPort: 80
       affinity:
         podAntiAffinity:  # affinity and Anti-Affinity setup here 
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - mango
               topologyKey: kubernetes.io/hostname
