apiVersion: apps/v1
kind: Deployment
metadata:
  name: podaffr
spec:
   replicas: 1
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - name: con1
         image: nginx:latest
         ports: 
         - containerPort: 80
       affinity:
         podAffinity:  # affinity and Anti-Affinity setup here 
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - mango
             topologyKey: kubernetes.io/hostname
