apiVersion: v1 
kind: Pod
metadata: 
   name: taintw2
   labels: 
      app: apple2
spec: 
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: color
    operator: Equal
    value: green
    effect: NoExecute

      #     node-role.kubernetes.io/control-plane:NoSchedule
