apiVersion: v1 
kind: Pod
metadata: 
   name: tainpod
   labels: 
      app: apple
spec: 
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

      #     node-role.kubernetes.io/control-plane:NoSchedule
