apiVersion: apps/v1
kind: Deployment
metadata:
  name: applivhttp
spec:
   replicas: 1
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - name: con1
         image: nginx:latest
         ports: 
         - containerPort: 80
         livenessProbe:
           httpGet:
             path: /abc/index.html
             port: 80
           initialDelaySeconds: 10
           periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
     app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

