apiVersion: v1 
kind: Pod
metadata: 
   name: test
   labels: 
      app: myapp
spec: 
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "1"
        memory: "128Mi"
      limits:
        cpu: "2"
        memory: "256Mi"
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080

