apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devopsrole
  namespace: devops
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - update
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - create
  - delete
